# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  hono-poc:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    image: hono-poc
    ports:
      - "8081:8081"
