# syntax=docker.io/docker/dockerfile:1.6.0

ARG NODE_IMAGE_URL=${NODE_IMAGE_URL:-docker.io/node}
ARG NODE_IMAGE_VERSION=${NODE_IMAGE_VERSION:-22.14.0-bookworm-slim}

ARG ORG_OPENCONTAINERS_IMAGE_AUTHORS=${ORG_OPENCONTAINERS_IMAGE_AUTHORS:-}
ARG ORG_OPENCONTAINERS_IMAGE_BASE_DIGEST=${ORG_OPENCONTAINERS_IMAGE_BASE_DIGEST:-}
ARG ORG_OPENCONTAINERS_IMAGE_BASE_NAME=${ORG_OPENCONTAINERS_IMAGE_BASE_NAME:-}
ARG ORG_OPENCONTAINERS_IMAGE_CREATED=${ORG_OPENCONTAINERS_IMAGE_CREATED:-}
ARG ORG_OPENCONTAINERS_IMAGE_DESCRIPTION=${ORG_OPENCONTAINERS_IMAGE_DESCRIPTION:-}
ARG ORG_OPENCONTAINERS_IMAGE_DOCUMENTATION=${ORG_OPENCONTAINERS_IMAGE_DOCUMENTATION:-}
ARG ORG_OPENCONTAINERS_IMAGE_LICENSES=${ORG_OPENCONTAINERS_IMAGE_LICENSES:-}
ARG ORG_OPENCONTAINERS_IMAGE_REF_NAME=${ORG_OPENCONTAINERS_IMAGE_REF_NAME:-}
ARG ORG_OPENCONTAINERS_IMAGE_REVISION=${ORG_OPENCONTAINERS_IMAGE_REVISION:-}
ARG ORG_OPENCONTAINERS_IMAGE_SOURCE=${ORG_OPENCONTAINERS_IMAGE_SOURCE:-}
ARG ORG_OPENCONTAINERS_IMAGE_TITLE=${ORG_OPENCONTAINERS_IMAGE_TITLE:-}
ARG ORG_OPENCONTAINERS_IMAGE_URL=${ORG_OPENCONTAINERS_IMAGE_URL:-}
ARG ORG_OPENCONTAINERS_IMAGE_VENDOR=${ORG_OPENCONTAINERS_IMAGE_VENDOR:-}
ARG ORG_OPENCONTAINERS_IMAGE_VERSION=${ORG_OPENCONTAINERS_IMAGE_VERSION:-}

ARG CLIENT_DATABASE_URI=${CLIENT_DATABASE_URI:-mysql://mysql_user:mysql_password@127.0.0.1:3306/hono-poc?charset=utf8mb4&connectionLimit=1}
ARG CLIENT_ELASTICSEARCH_NODE=${CLIENT_ELASTICSEARCH_NODE:-http://elasticsearch:9200}
ARG CLIENT_REDIS_URL=${CLIENT_REDIS_URL:-redis://redis:6379}
ARG HUSKY=${HUSKY:-HUSKY}
ARG NODE_ENV=${NODE_ENV:-development}
ARG PNPM_VERSION=${PNPM_VERSION:-10.6.5}
ARG SERVER_PORT=${SERVER_PORT:-8081}

FROM ${NODE_IMAGE_URL}:${NODE_IMAGE_VERSION}

ARG ORG_OPENCONTAINERS_IMAGE_AUTHORS
ARG ORG_OPENCONTAINERS_IMAGE_BASE_DIGEST
ARG ORG_OPENCONTAINERS_IMAGE_BASE_NAME
ARG ORG_OPENCONTAINERS_IMAGE_CREATED
ARG ORG_OPENCONTAINERS_IMAGE_DESCRIPTION
ARG ORG_OPENCONTAINERS_IMAGE_DOCUMENTATION
ARG ORG_OPENCONTAINERS_IMAGE_LICENSES
ARG ORG_OPENCONTAINERS_IMAGE_REF_NAME
ARG ORG_OPENCONTAINERS_IMAGE_REVISION
ARG ORG_OPENCONTAINERS_IMAGE_SOURCE
ARG ORG_OPENCONTAINERS_IMAGE_TITLE
ARG ORG_OPENCONTAINERS_IMAGE_URL
ARG ORG_OPENCONTAINERS_IMAGE_VENDOR
ARG ORG_OPENCONTAINERS_IMAGE_VERSION

ARG CLIENT_DATABASE_URI
ARG CLIENT_ELASTICSEARCH_NODE
ARG CLIENT_REDIS_URL
ARG HUSKY
ARG NODE_ENV
ARG PNPM_VERSION
ARG SERVER_PORT

LABEL org.opencontainers.image.authors=${ORG_OPENCONTAINERS_IMAGE_AUTHORS}
LABEL org.opencontainers.image.base.digest=${ORG_OPENCONTAINERS_IMAGE_BASE_DIGEST}
LABEL org.opencontainers.image.base.name=${ORG_OPENCONTAINERS_IMAGE_BASE_NAME}
LABEL org.opencontainers.image.created=${ORG_OPENCONTAINERS_IMAGE_CREATED}
LABEL org.opencontainers.image.description=${ORG_OPENCONTAINERS_IMAGE_DESCRIPTION}
LABEL org.opencontainers.image.documentation=${ORG_OPENCONTAINERS_IMAGE_DOCUMENTATION}
LABEL org.opencontainers.image.licenses=${ORG_OPENCONTAINERS_IMAGE_LICENSES}
LABEL org.opencontainers.image.ref.name=${ORG_OPENCONTAINERS_IMAGE_REF_NAME}
LABEL org.opencontainers.image.revision=${ORG_OPENCONTAINERS_IMAGE_REVISION}
LABEL org.opencontainers.image.source=${ORG_OPENCONTAINERS_IMAGE_SOURCE}
LABEL org.opencontainers.image.title=${ORG_OPENCONTAINERS_IMAGE_TITLE}
LABEL org.opencontainers.image.url=${ORG_OPENCONTAINERS_IMAGE_URL}
LABEL org.opencontainers.image.vendor=${ORG_OPENCONTAINERS_IMAGE_VENDOR}
LABEL org.opencontainers.image.version=${ORG_OPENCONTAINERS_IMAGE_VERSION}

ENV CLIENT_DATABASE_URI=${CLIENT_DATABASE_URI}
ENV CLIENT_ELASTICSEARCH_NODE=${CLIENT_ELASTICSEARCH_NODE}
ENV CLIENT_REDIS_URL=${CLIENT_REDIS_URL}
ENV HUSKY=${HUSKY}
ENV NODE_ENV=${NODE_ENV}
ENV PNPM_VERSION=${PNPM_VERSION}
ENV SERVER_PORT=${SERVER_PORT}

RUN export DEBIAN_FRONTEND=noninteractive \
  && apt update \
  && apt --yes upgrade \
  && apt --yes install --no-install-recommends \
    wget \
  && apt clean \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/node/hono-poc/

COPY ./package.json ./pnpm-lock.yaml ./
COPY ./script/husky.install.js ./script/
RUN npm install --global pnpm@9.12.0 \
  && pnpm install --frozen-lockfile

COPY --chown=node:node . .

RUN pnpm run build

# USER node
EXPOSE ${SERVER_PORT}
CMD ["node", "./build/app.node.js"]
