@startuml UserPOCView UseCase Delete
actor Client
Client -> DrivingUserPOCViewDelete
DrivingUserPOCViewDelete -> UseCaseUserPOCViewDelete: execute
UseCaseUserPOCViewDelete -> UseCaseUserPOCInformationDeleteUserID: execute
UseCaseUserPOCInformationDeleteUserID --> UseCaseUserPOCViewDelete: { id }
UseCaseUserPOCViewDelete -> UseCaseUserPOCDelete: execute
UseCaseUserPOCDelete --> UseCaseUserPOCViewDelete: { id }
UseCaseUserPOCViewDelete --> DrivingUserPOCViewDelete: { id }
DrivingUserPOCViewDelete --> Client
@enduml
