@startuml UserPOCView UseCase Update
actor Client
Client -> DrivingUserPOCViewUpdate
DrivingUserPOCViewUpdate -> UseCaseUserPOCViewUpdate: execute
UseCaseUserPOCViewUpdate -> UseCaseUserPOCInformationUpdateUserID: execute
UseCaseUserPOCInformationUpdateUserID --> UseCaseUserPOCViewUpdate: { id }
UseCaseUserPOCViewUpdate -> UseCaseUserPOCUpdate: execute
UseCaseUserPOCUpdate --> UseCaseUserPOCViewUpdate: { id }
UseCaseUserPOCViewUpdate --> DrivingUserPOCViewUpdate: { id }
DrivingUserPOCViewUpdate --> Client
@enduml
