// This file is generated by icon spritesheet generator

export const iconNames = [
  "outlinr-search",
  "outline-warning",
  "outline-username",
  "outline-url",
  "outline-success",
  "outline-phone",
  "outline-password",
  "outline-info",
  "outline-error",
  "outline-email",
  "outline-document",
] as const;

export type IconName = (typeof iconNames)[number];
