@startuml UserPOCInformation UseCase ReadID
actor Client
Client -> DrivingUserPOCInformationReadID
DrivingUserPOCInformationReadID -> UseCaseUserPOCInformationReadID: execute
UseCaseUserPOCInformationReadID -> DrivenUserPOCInformationReadID: read
DrivenUserPOCInformationReadID --> UseCaseUserPOCInformationReadID: DomainUserPOCInformation
UseCaseUserPOCInformationReadID --> DrivingUserPOCInformationReadID: DomainUserPOCInformation
DrivingUserPOCInformationReadID --> Client
@enduml
