// This file is generated by icon spritesheet generator

export const iconNames = [
  "outline-warning",
  "outline-success",
  "outline-info",
  "outline-error",
] as const;

export type IconName = (typeof iconNames)[number];
