apiVersion: 1

datasources:
  - access: proxy
    editable: false
    jsonData:
      derivedFields:
        - datasourceUid: "tempo"
          matcherRegex: "trace_id"
          matcherType: "label"
          name: "trace_id"
          url: "$${__value.raw}"
          urlDisplayLabel: "Trace: $${__value.raw}"
    name: Loki
    type: loki
    uid: loki
    url: http://127.0.0.1:3100

  - access: proxy
    editable: false
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: trace_id
          urlDisplayLabel: "Trace: $${__value.raw}"
      timeInterval: 60s
    name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://127.0.0.1:9090

  - access: proxy
    editable: false
    jsonData:
      backendType: pyroscope
      # basicAuth: true
      # basicAuthUser: '123456'
      keepCookies: [GitSession]
    name: Pyroscope
    secureJsonData:
      # basicAuthPassword: PASSWORD
    type: grafana-pyroscope-datasource
    uid: pyroscope
    url: http://pyroscope:4040

  - access: proxy
    editable: false
    jsonData:
      tracesToLogsV2:
        customQuery: true
        datasourceUid: "loki"
        query: '{$${__tags}} | trace_id = "$${__trace.traceId}"'
        tags:
          - key: "service.name"
            value: "service_name"
      lokiSearch:
        datasourceUid: "loki"
      nodeGraph:
        enabled: true
      search:
        hide: false
      serviceMap:
        datasourceUid: "prometheus"
    name: Tempo
    type: tempo
    uid: tempo
    url: http://127.0.0.1:3200
